### ISSUE TITLE
Regression involving rtosc

### ISSUE THREAD

**Issue by ZigTag** [zynaddsubfx/zynaddsubfx#246]
On the newest commit, zynaddsubfx fails to build using the zyn-fusion-scripts that are available on the organization. I found that reverting to an old commit of rtosc (I used "544857c") solved the issue. It seems like a refactor of the port checker breaks the liblo import on it. I also found that when `#include <stdint.h>` is not included on any file that has int64_t, it will make the build fail with error: 'int64_t' does not name a type.

I was testing using the MinGW toolchain however it seemed to be happening using WSL with the cross-build. I'd check to see if there's any more elegant solution.

**Comment by fundamental** [comment]
I've reverted the commit which moved port-checker code into the rtosc core shared/static library as that would be a large change of scope for rtosc (IMO). In theory updating the submodule version should resolve the issue, though there may be some alternative reorganizations proposed by @JohannesLorenz

**Comment by JohannesLorenz** [comment]
> I've reverted the commit which moved port-checker code into the rtosc core shared/static library as that would be a large change of scope for rtosc (IMO).

I propose seeing this from another perspective. rtosc-cpp consists mostly of extensions that are not required for OSC - e.g. miditable, undo-history, automation, savefiles. On the contrary, port-checker is focused on validating the core. I don't see port-checker as an extension - looking at how many issues we had in zyn I see port-checker as a requirement to write syntactically correct OSC ports.

What's the alternative? I could start building a separate lib like librtosc-portchecker.so. But I would rather suggest to create libs for the extensions: librtosc-miditable.so, librtosc-undo-history.so etc, and leave the core-feature "port-checker" inside the cpp lib.

**Comment by JohannesLorenz** [comment]
A further problem is that the rtosc commit was reverted, but not the zyn commit. The next time that anyone will update the rtosc submodule, they will get compile issues in zyn.

**Comment by fundamental** [comment]
Apologies for the delayed response. So, for rtosc, there's a fair amount of scope creep outside of the core OSC layer, but one location where I do think a hard boundary should be set is making rtosc \*dependent\* on another library or any networking stack. Either option limits the portability of the library.

I'm 100% fine with the vast majority of the port checking logic to shift into the scope of the project, but anything involving liblo would have to be either an add on utility or a unit test. It might seem a bit silly, but for the port-checker code that would be factoring out the code in the server class and the handle_st() code out of the core.

**Comment by JohannesLorenz** [comment]
@fundamental Thanks for explaining. Now I understand better what you mean.

I was able to move the liblo code into a separate, virtual subclass. The last part I'm not sure about is how to make this `liblo_server` class visible to both the zyn tests and the two rtosc tests, without putting it in the rtosc includes/libs. My best idea is to put the headers and libs into the rtosc test directories (src and cmake build). It's still weird because then the zyn tests now include/link the rtosc test directories. Does that make sense to you, or would you propose another location?

Alternatively, I can duplicate the new `liblo_server` class sources into rtosc *and* zyn test directories. This has the disadvantage of redundancy, but the advantage of not linking to rtosc's test directory.

**Comment by fundamental** [comment]
I'd lean towards zyn tests having a dependent target that's defined in the rtosc tests. It's messy in its own way, but at least it avoids code duplication which increases the chances that there's a desync between the projects.

**Comment by JohannesLorenz** [comment]
> zyn tests having a dependent target that's defined in the rtosc tests

What kind of target do you mean? A library for `liblo_server`?

**Comment by pgervais** [comment]
FWIW, here's the PR pushing rtosc past the revert in zynaddsubfx: https://github.com/zynaddsubfx/zynaddsubfx/pull/248

**Comment by pgervais** [comment]
As anticipated by JohannedLorenz, pushing the rtosc version in zynaddsubfx without reverting the full change breaks the build on Linux.

**Comment by JohannesLorenz** [comment]
> FWIW, here's the PR pushing rtosc past the revert in zynaddsubfx: #248

Thanks a lot for your help, but I already have a branch waiting that should fix it all correctly, according to the discussion comments.

> What kind of target do you mean? A library for `liblo_server`?

@fundamental It would be nice if you would help advancing with this issue (by assisting me if I have questions). It is open for 2 weeks already.

**Comment by fundamental** [comment]
Ah, I was assuming that the question was more of a naming convention issue, not a blocker upon rereading it's a bit more clear, though I'm not sure my response is the information needed to unblock.

So, in rtosc's port-checker.h we have handle_st() (2 instances), lo_server, lo_address, and on_recv(). Factoring those out we should be able to get rid of the first handle_st(), and the second class 'server' could be made a base class for the implemented test, with the base class not referencing anything liblo specific.

Then the proposed `liblo_server` class could be stored outside of the base library. In this case the functionality of the liblo_server subclass of 'rtosc::port_checker::server' would be roughly 50 LOC. It's possible and fine to define code in rtosc test which would work as an include only header to be used in zyn's tests, it's also possible to have a private library (i.e. `add_library()` in CMake without specifying STATIC or SHARED). I'd propose using the private library version in rtosc and linking that to the zyn test as needed. I don't mind the repeated code or keeping it as an include only header within the test folder if you find that to be a simpler option.

**Comment by JohannesLorenz** [comment]
The liblo issues should be fixed on master now, any testing would be appreciated.

**Comment by fundamental** [comment]
Using the docker builder a failure still occurs, though hopefully it should be just a matter of re-disabling pkg-config on those systems.

**Comment by fundamental** [comment]
The build appears to now be restored using the docker based ubuntu crossbuild
